Laboratorium 2/Models/Birth.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Laboratorium_2.Models
{
    public class Birth
    {
        [Required(ErrorMessage = "Pole 'Imię' jest wymagane.")]
        public string Imie { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Data urodzenia")]
        [Required(ErrorMessage = "Pole 'Data urodzenia' jest wymagane.")]
        public DateTime DataUrodzenia { get; set; }

        public bool IsValid()
        {
            return !string.IsNullOrEmpty(Imie) && DataUrodzenia < DateTime.Now;
        }
    }
}

Laboratorium 2/Models/Calculator.cs
using System.Numerics;

namespace Laboratorium_2.Models
{ 
    public enum Operators
    {
        Unknown, Add, Mul, Sub, Div
    }
    public class Calculator
    {
        public Operators? Operator { get; set; }
        public double? X { get; set; }
        public double? Y { get; set; }

        public String Op
        {
            get
            {
                switch (Operator)
                {
                    case Operators.Add:
                        return "+";
                    case Operators.Mul:
                        return "*";
                    case Operators.Div:
                        return "/";
                    case Operators.Sub:
                        return "-";
                    case Operators.Unknown:
                        return "?";
                default:
                        return "";
                }
            }
        }

        public bool IsValid()
        {
            return Operator != null && X != null && Y != null;
        }

        public double Calculate()
        {
            switch (Operator)
            {
                case Operators.Add:
                    return (double)(X + Y);
                case Operators.Sub:
                    return (double)(X - Y);
                case Operators.Mul: 
                    return (double)(X * Y);
                case Operators.Div:
                //sprawdzam czy y nie jest zerem
                return Y != 0 ? (double)(X / Y) : double.NaN;
            default: return double.NaN;

            }
        }
    }
}

Laboratorium 2/Models/ErrorViewModel.cs
namespace Laboratorium_2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Laboratorium 2/Controllers/BirthController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;

namespace Laboratorium_2.Controllers
{
    public class Birth
    {
        [Required(ErrorMessage = "Pole 'Imię' jest wymagane.")]
        public string Imie { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Data urodzenia")]
        [Required(ErrorMessage = "Pole 'Data urodzenia' jest wymagane.")]
        public DateTime DataUrodzenia { get; set; }

        public bool IsValid()
        {
            return !string.IsNullOrEmpty(Imie) && DataUrodzenia < DateTime.Now;
        }
    }
    public class BirthController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(Birth model)
        {
            if (ModelState.IsValid && model.IsValid())
            {
                int wiek = ObliczWiek(model.DataUrodzenia);
                ViewBag.Message = $"Cześć {model.Imie}, masz {wiek} lat(a).";
            }
            else
            {
                ViewBag.Message = "Błąd: Niepoprawne dane.";
            }
            return View();
        }

        private int ObliczWiek(DateTime dataUrodzenia)
        {
            DateTime dzisiaj = DateTime.Today;
            int wiek = dzisiaj.Year - dataUrodzenia.Year;
            if (dataUrodzenia.Date > dzisiaj.AddYears(-wiek))
            {
                wiek--;
            }
            return wiek;
        }

    }
}

Laboratorium 2/Controllers/CalculatorController.cs
using Laboratorium_2.Models;
using Microsoft.AspNetCore.Mvc;

namespace Laboratorium_2.Controllers
{
    public class CalculatorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Result(Calculator model)
        {
            if (!model.IsValid())
            {
                return View("Error");
            }
            return View(model);
        }
        public enum Operators
        {
            Unknown, Add, Mul, Sub, Div
        }
        public IActionResult Form()
        {
            return View();
        }

    }

}

Laboratorium 2/Controllers/HomeController.cs
using Laboratorium_2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Laboratorium_2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Laboratorium 2/Views/Birth/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Birth

<h2>Wprowadź swoje dane:</h2>

<form asp-controller="Birth" asp-action="Index" method="post">
    <div class="form-group">
        <label for="Imie">Imię:</label>
        <input asp-for="Imie" class="form-control" />
    </div>
    <div class="form-group">
        <label for="DataUrodzenia">Data urodzenia:</label>
        <input asp-for="DataUrodzenia" type="date" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Sprawdź</button>
</form>

@if (ViewBag.Message != null)
{
    <div class="mt-4">
        <strong>@ViewBag.Message</strong>
    </div>
}

Laboratorium 2/Views/Calculator/Form.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6">
            <h2>Kalkulator</h2>
            <form action="Result" method="POST">
                <div class="mb-3">
                    <label class="form-label" for="x">Liczba 1</label>
                    <input class="form-control" type="number" name="x" step="0.00001" id="x" />
                </div>
                <div class="mb-3">
                    <label class="form-label" for="operator">Operator</label>
                    <select name="operator">
                        <option value="add">+</option>
                        <option value="sub">&minus;</option>
                        <option value="mul">&times;</option>
                        <option value="div">&divide;</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="y">Liczba 2</label>
                    <input class="form-control" type="number" name="Y" step="0.00001" id="y" />
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">Oblicz</button>
                </div>
            </form>
        </div>
    </div>
</div>

Laboratorium 2/Views/Calculator/Result.cshtml
@model Calculator
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<H3>@Model.X @Model.Op @Model.Y </H3>
<h1>@Model.Calculate()</h1>

Laboratorium 2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Laboratorium_2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Laboratorium_2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Laboratorium_2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Form">Kalkulator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Birth" asp-action="Index">BirthController</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Laboratorium_2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>